package aformela.zad02.service;
import java.sql.*;

import aformela.zad02.domain.Bird;

public class BirdService {
	private Connection connection;

    private String url = "jdbc:hsqldb:hsql://localhost/workdb";

    private String createTableBird = "CREATE TABLE Bird(id bigint GENERATED BY DEFAULT AS IDENTITY, name varchar(30), date_of_birth date, is_female boolean, weight double)";

    private Statement statement;

    public BirdService(){
        try{
           connection = DriverManager.getConnection(url);
           statement = connection.createStatement();

            ResultSet resultSet = connection.getMetaData().getTables(null,null,null,null);
            boolean tableExists = false;
            while (resultSet.next()){
                if("Bird".equalsIgnoreCase(resultSet.getString("table_name"))){
                    tableExists = true;
                    break;
                }
            }
            if(!tableExists){
                statement.executeUpdate(createTableBird);
            }

        }catch (SQLException e){
            e.printStackTrace();
        }
    }

    public void addBird(Bird bird) throws SQLException {
        String addBirdSql = "INSERT INTO Bird (name ,date_of_birth ,is_female, weight) VALUES " +
                "(\'" + bird.getName() + "\' ,\'" + bird.getDateOfBirth() + "\' ," + bird.isFemale() + " ," + bird.getWeight() + "\')";
        statement.executeUpdate(addBirdSql);
    }

    //todo: implement method deleteDog
    public void deleteBird(Bird bird) throws SQLException {
        ResultSet resultSet = statement.executeQuery("SELECT id FROM Bird WHERE name="+bird.getName());
        String deleteBirdSql = "DELETE FROM Bird WHERE id=";
        statement.executeUpdate(deleteBirdSql);
    }
}
